#######################
#    BETA TESTEURS
#######################
parameters:
    betatesteurs: ~
#        - { key: "Localhost",                         ip: "127.0.0.1",       login: "*"           } 
#        - { key: "Michel UBEDA (MRS)",                ip: "195.221.209.45",  login: "mubeda"      }
        
      