parameters:
    app.use_cdn: true
    app.cdn.local: "bundles/app/cdn/" 
    app.cdn: 
    # - { name: "nom de référence",  type: "js/css/json/...",  url: "lien sans 'http://' ..."  } 
    #      +optionnel => isRequiered: true, useLocal: false
    # CDN : http://cdnjs.com/ [ le CDN le plus à jour... ]
    # CDN : http://www.jsdelivr.com/
    # CDN : https://developers.google.com/speed/libraries/devguide?hl=fr
    
    # Librairies jquery/ui = testé et validé ; si usage last version focus MENU = bizare
      - { name: "jquery",               type: "js",     url: "ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" }
      - { name: "jquery_ui",            type: "js",     url: "ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"}
      - { name: "jquery_ui_theme",      type: "css",    url: "ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/redmond/jquery-ui.min.css" }
      
      - { name: "font_Oswald",          type: "font",   url: "fonts.googleapis.com/css?family=Oswald:400,300,700" }
      - { name: "font_OpenSans",        type: "font",   url: "fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,300,700" }
      - { name: "font_Lustria",         type: "font",   url: "fonts.googleapis.com/css?family=Lustria" }
      
      - { name: "dataTables_jqTh",      type: "css",    url: "cdn.datatables.net/1.10.4/css/jquery.dataTables_themeroller.css" }
      - { name: "dataTables",           type: "js",     url: "cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js" }
#      - { name: "dataTables_jqTh",      type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/datatables/1.10.4/css/jquery.dataTables_themeroller.css" }
#      - { name: "dataTables",           type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/datatables/1.10.4/js/jquery.dataTables.min.js" }
      - { name: "dataTables_fxHeader",  type: "css",    url: "cdn.datatables.net/fixedheader/2.1.2/css/dataTables.fixedHeader.css" }
      - { name: "dataTables-fxHeader",  type: "js",     url: "cdn.datatables.net/fixedheader/2.1.2/js/dataTables.fixedHeader.min.js" }
#      - { name: "dataTables_Fr",       type: "json",   url: "cdn.datatables.net/plug-ins/725b2a2115b/i18n/French.json" }

      - { name: "select2",              type: "js",    url: "cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.js" }
      - { name: "select2",              type: "css",   url: "cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.css" }

      - { name: "chosen",               type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.min.js" }
      - { name: "chosen",               type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.min.css" }
 
      # http://trentrichardson.com/examples/timepicker/
#      - { name: "timepicker",           type: "js",     url: "cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.js"  }
#      - { name: "timepicker",           type: "css",    url: "cdn.jsdelivr.net/jquery.ui.timepicker.addon/1.4.5/jquery-ui-timepicker-addon.css" }

      - { name: "timepicker",           type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.css" }
      - { name: "timepicker",           type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/jquery-ui-timepicker-addon.min.js"  }
      - { name: "timepicker",           type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.4.5/i18n/jquery-ui-timepicker-fr.js"  }


      # http://bgrins.github.io/spec  trum/
      - { name: "spectrum",             type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/spectrum/1.6.0/spectrum.min.css" }
      - { name: "spectrum",             type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/spectrum/1.6.0/spectrum.min.js" }
      #- { name: "spectrum",             type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/spectrum/1.6.0/i18n/jquery.spectrum-fr.min.js" }
      

       # slidebars doit être activé  si dans app.yml => 'app.message: true'
      # https://github.com/adchsm/Slidebars
      - { name: "slidebars",            type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/slidebars/0.10.2/slidebars.min.js" }    
      - { name: "slidebars",            type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/slidebars/0.10.2/slidebars.min.css"}

      #- { name: "jquery-migrate",       type: "js",     url: "code.jquery.com/jquery-migrate-1.2.1.min.js" }
      - { name: "jquery-migrate",       type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js" }
      - { name: "swfobject",            type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/swfobject/2.2/swfobject.min.js" }
      - { name: "ZeroClipboard",        type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js" }
      - { name: "hoverIntent_r7",       type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/jquery.hoverintent/2013.03.11/hoverintent.min.js" }
      #- { name: "hoverIntent_r7",       type: "js",     url: "bundles/app/js/hoverintent.min.js", useLocal: true  }


# LOCALS REQUIERED

      - { name: "cluetip",        type: "css",    url: "bundles/app/js/cluetip/jquery.cluetip-amu.css", useLocal: true }
      - { name: "cluetip",        type: "js",     url: "bundles/app/js/cluetip/jquery.cluetip.min.js", useLocal: true }

      - { name: "tablesorter",    type: "js",     url: "bundles/app/js/jquery.tablesorter.min.js", useLocal: true }
      - { name: "tablesorter",    type: "css",    url: "bundles/app/css/tablesorter.css", useLocal: true }
#      - { name: "tablesorter",    type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.18.4/js/jquery.tablesorter.min.js" }
#      - { name: "tablesorter",    type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.18.4/css/theme.jui.css" }


#      - { name: "ckeditor",     type: "js",     url: "bundles/ivoryckeditor/ckeditor.js", useLocal: true  }

# OPTIONALS (désactivé par défaut)

      # https://github.com/stanlemon/jGrowl Activé si app.notifications: "jgrowl" / ["...","jgrowl"]

#      - { name: "jgrowl",        type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.2.12/jquery.jgrowl.min.css"  }    
#      - { name: "jgrowl",        type: "js",    url: "cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.2.12/jquery.jgrowl.min.js"  }    


      # http://sanderkorvemaker.nl/jquery/jLorem.php 
      # lorem Peux être désactivé si DemoBundle n'est pas chargé...
      - { name: "lorem",        type: "js",    url: "bundles/app/js/jquery.lorem.min.js", useLocal: true }    

      # http://www.highcharts.com/ 
#      - { name: "highcharts",          type: "js",     url: "code.highcharts.com/highcharts.js",        only:["_demo_highcharts"] }
#      - { name: "highcharts-more",     type: "js",     url: "code.highcharts.com/highcharts-more.js",   only:["_demo_highcharts"] }
#      - { name: "highcharts-export",   type: "js",     url: "code.highcharts.com/modules/exporting.js", only:["_demo_highcharts"] }
      
      # highcharts... Peux être désactivé si DemoBundle n'est pas chargé...
      - { name: "highcharts",          type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/highcharts/4.0.4/highcharts.js",        only:["_demo_highcharts"] }
      - { name: "highcharts-more",     type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/highcharts/4.0.4/highcharts-more.js",   only:["_demo_highcharts"] }    
      - { name: "highcharts-export",   type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/highcharts/4.0.4/modules/exporting.js", only:["_demo_highcharts"] }

# ATTENTION GARDER les librairies ci-dessous EN DERNIER (gestion des dépendances)

      - { name: "cke_contents", type: "css",    url: "bundles/app/css/cke_contents.css", useLocal: true }
#      - { name: "jq_tooltip",   type: "css",    url: "bundles/app/css/jquery.tooltips.css", useLocal: true }
      - { name: "sf-forms",     type: "css",    url: "bundles/app/css/symfony-forms.css", useLocal: true }
      - { name: "perso",        type: "css",    url: "bundles/app/css/perso.css", useLocal: true }
      - { name: "amu_css",      type: "css",    url: "bundles/app/css/amu.css", useLocal: true }
      - { name: "amu",          type: "js",     url: "bundles/app/js/amu.js", useLocal: true }
