parameters:
    app.use_cdn: true
    app.cdn.local: "bundles/app/cdn/" 
    app.cdn: 
    # - { name: "nom de référence",  type: "js/css/json/...",  url: "lien sans 'http://' ..."  } 
    #      +optionnel => isRequiered: true, useLocal: false
    # CDN : https://developers.google.com/speed/libraries/devguide?hl=fr
    # CDN : http://cdnjs.com/
    # CDN : http://www.jsdelivr.com/
    
      - { name: "jquery",              type: "js",     url: "ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" }
      - { name: "jquery_ui",           type: "js",     url: "ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"}
      - { name: "jquery_ui_theme",     type: "css",    url: "ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/redmond/jquery-ui.min.css" }
      
      - { name: "font_Oswald",         type: "font",   url: "fonts.googleapis.com/css?family=Oswald:400,300,700" }
      - { name: "font_OpenSans",       type: "font",   url: "fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,300,700" }
      - { name: "font_Lustria",        type: "font",   url: "fonts.googleapis.com/css?family=Lustria" }
      
      - { name: "dataTables_jQth",     type: "css",    url: "cdn.datatables.net/1.10.2/css/jquery.dataTables_themeroller.css" }
      - { name: "dataTables_fxHeader", type: "css",    url: "cdn.datatables.net/fixedheader/2.1.2/css/dataTables.fixedHeader.css" }
      - { name: "dataTables",          type: "js",     url: "cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js" }
      - { name: "dataTables-fxHeader", type: "js",     url: "cdn.datatables.net/fixedheader/2.1.2/js/dataTables.fixedHeader.min.js" }
      - { name: "dataTables_Fr",       type: "json",   url: "cdn.datatables.net/plug-ins/725b2a2115b/i18n/French.json" }
           
      - { name: "jquery-migrate",      type: "js",     url: "code.jquery.com/jquery-migrate-1.2.1.js" }
      - { name: "swfobject",           type: "js",     url: "ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js" }
      - { name: "ZeroClipboard",       type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.1.5/ZeroClipboard.min.js" }

# LOCALS REQUIERED
      - { name: "amu",          type: "css",    url: "bundles/app/css/amu.css", useLocal: true }
      - { name: "perso",        type: "css",    url: "bundles/app/css/perso.css", useLocal: true }
      - { name: "sf-forms",     type: "css",    url: "bundles/app/css/symfony-forms.css", useLocal: true }
      - { name: "dataTables_jQ",type: "css",    url: "bundles/app/css/jquery.dataTables_themeroller.css", useLocal: true }
      
      - { name: "hoverIntent",  type: "js",     url: "bundles/app/js/jquery.hoverIntent.minified.js", useLocal: true }
      
      - { name: "slidebars",    type: "css",    url: "bundles/app/js/slidebars/slidebars.min.css", useLocal: true }
      - { name: "slidebars",    type: "js",     url: "bundles/app/js/slidebars/slidebars.min.js", useLocal: true }

      - { name: "select2",      type: "css",    url: "bundles/app/js/select2/select2.css", useLocal: true }
      - { name: "select2",      type: "js",     url: "bundles/app/js/select2/select2.min.js", useLocal: true }

      - { name: "chosen",       type: "css",    url: "bundles/app/js/chosen/chosen.css", useLocal: true }
      - { name: "chosen",       type: "js",     url: "bundles/app/js/chosen/chosen.jquery.min.js", useLocal: true }

      - { name: "spectrum",     type: "css",    url: "bundles/app/js/spectrum/jquery.spectrum.css", useLocal: true }
      - { name: "spectrum",     type: "js",     url: "bundles/app/js/spectrum/jquery.spectrum.js", useLocal: true }
      
      - { name: "cluetip",      type: "css",    url: "bundles/app/js/cluetip/jquery.cluetip.css", useLocal: true }
      - { name: "cluetip",      type: "js",     url: "bundles/app/js/cluetip/jquery.cluetip.js", useLocal: true }

      - { name: "tablesorter",  type: "css",    url: "bundles/app/css/tablesorter.css", useLocal: true }
      - { name: "tablesorter",  type: "js",     url: "bundles/app/js/jquery.tablesorter.min.js", useLocal: true }

      - { name: "timepicker",   type: "css",    url: "bundles/app/css/jquery-ui-timepicker-addon.css", useLocal: true }
      - { name: "timepicker",   type: "js",     url: "bundles/app/js/jquery-ui-timepicker-addon.js", useLocal: true }

# OPTIONALS (désactivé par défaut)

      # http://sanderkorvemaker.nl/jquery/jLorem.php
#      - { name: "lorem",        type: "js",    url: "bundles/app/js/jquery.lorem.min.js", useLocal: true }    

      # http://fullcalendar.io/
      
# ver 2.1.11 (à tester)      
#      - { name: "fullcalendar",        type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.1.1/fullcalendar.css" }
#      - { name: "fullcalendar_print",  type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.1.1/fullcalendar.print.css" }
##       - { name: "fullcalendar",        type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.js" }
#      - { name: "moment",              type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.2/moment.min.js" }
#      - { name: "fullcalendar",        type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.1.1/fullcalendar.min.js" }
#      - { name: "fullcalendar-gcal",   type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.1.1/gcal.js" }
# ver 1.6.4 (OK)
#      - { name: "fullcalendar",        type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css" }
#      - { name: "fullcalendar_print",  type: "css",    url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.print.css" }
#      - { name: "fullcalendar",        type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js" }
#      - { name: "fullcalendar-gcal",   type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/gcal.js" }

      # http://www.highcharts.com/ 
#      - { name: "highcharts",          type: "js",     url: "code.highcharts.com/highcharts.js" }
#      - { name: "highcharts-more",     type: "js",     url: "code.highcharts.com/highcharts-more.js" }
#      - { name: "highcharts-export",   type: "js",     url: "code.highcharts.com/modules/exporting.js" }
            
      
      # http://hayageek.com/docs/jquery-upload-file.php uploadFile en Ajax cf exemple dans projet PACBO
#      - { name: "uploadfile",           type: "css",     url: "hayageek.github.io/jQuery-Upload-File/uploadfile.min.css" }
#      - { name: "uploadfile",           type: "js",     url: "hayageek.github.io/jQuery-Upload-File/jquery.uploadfile.min.js" }
    
      # http://malsup.com/jquery/block/ blockage d'une partie de l'ihm  + flashMessage en ajax
#      - { name: "blockUI",           type: "js",     url: "cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.66.0-2013.10.09/jquery.blockUI.min.js" }
     
      
# ATTENTION GARDER amu.js en dernier (gestion des dépendances)      
      
      - { name: "amu",          type: "js",     url: "bundles/app/js/amu.js", useLocal: true }
