#######################
#    DEVELOPPERS
#######################
parameters:
    developpers:
        - { key: "VPN",                               ip: "10.193.1.1",      login: "mubeda"           }
        - { key: "Localhost",                         ip: "127.0.0.1",       login: "*"                }
        - { key: "Pascal AVALLE (AIX)",               ip: "193.51.62.38",    login: "a03a2867"         }
        - { key: "Pascal AVALLE (MRS)",               ip: "195.221.209.70",  login: "a03a2867"         }
        - { key: "Christophe CAVALIER (MRS)",         ip: "195.221.209.13",  login: "christophe"       }
        - { key: "Jean-Philippe FLORET (MRS)",        ip: "195.221.209.47",  login: "a04a3347"         }
        - { key: "Arnaud SALVUCCI (LMY)",             ip: "139.124.44.37",   login: "salvucci"         }
        - { key: "Arnaud SALVUCCI (MRS)",             ip: "195.221.209.xx",  login: "salvucci"         }
        - { key: "Michel UBEDA (MRS)",                ip: "195.221.209.45",  login: "mubeda"           }
        - { key: "Michel UBEDA (portable)",           ip: "195.221.209.46",  login: "mubeda"           }
        - { key: "Peggy FERNANDEZ BLANCO",            ip: "147.94.140.8",    login: "pfernandezblanco" }