#############
#   ROLES   #
#############
parameters:
  roles_manager:
    
        - { name: "ROLE_MEMBRE",         type: "ldap2",    link: "",  values: "", filter: "(|(edupersonaffiliation=employee)(edupersonaffiliation=faculty)(edupersonaffiliation=researcher))" } 
        - { name: "ROLE_GESTIONNAIRE",   type: "ldap2",    link: "",  values: "", filter: "(memberof=cn=amu:app:grp:grouper:grouper-ent,ou=groups,dc=univ-amu,dc=fr)" } 
        - { name: "ROLE_DOSI",           type: "ldap2",    link: "",  values: "", filter: "(memberof=cn=amu:svc:dosi:tous,ou=groups,dc=univ-amu,dc=fr)" }
        - { name: "ROLE_ADMIN",          type: "ldap2",    link: "",  values: "", filter: "(memberof=cn=amu:adm:app:groupie,ou=groups,dc=univ-amu,dc=fr)" } 
        - { name: "ROLE_SUPER_ADMIN",    type: "session",  link: "_isDevelopper",  values: "1" } 
        #- { name: "ROLE_SUPER_ADMIN",    type: "ldap2",  link: "",  values: "", filter: "(memberof=cn=amu:adm:app:bo,ou=groups,dc=univ-amu,dc=fr)" }  
    
    # EXEMPLE Role accordé en fonction d'une chaine d'intérrogation ldap complexe...
 
      # amuSite=M301
      # amuCampus=L
      # amuComposante
      # supannAffectation=DOSI
      # supannEntiteAffectation=

    # EXEMPLES pour forcer des roles pour les développeurs :
#    - { name: "ROLE_PERSONAL",    type: "session",  link: "_isDevelopper",  values: "1" }
#    - { name: "ROLE_STUDENT",     type: "session",  link: "_isDevelopper",  values: "1" }
#    - { name: "ROLE_STUDENT2",    type: "session",  link: "_isDevelopper",  values: "1" }
#    - { name: "ROLE_STUDENT_ADM", type: "session",  link: "uid",            values: ["123456","7891011"] }
#    - { name: "ROLE_STUDENT_ADM", type: "session",  link: "login",            values: ["toto","titi","tutu"] }


