jms_security_extra:
    secure_all_services: false
    expressions: true
   
security:
            
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Amu\AppBundle\Security\User\AmuUser: plaintext

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:

    amu_users:
      id: amu_user_provider
      
    externals:
      entity: { class: AppBundle:ExternalAccounts, property: username }
           
    in_memory:
      memory:
        users:
          user:  { password: pass, roles: [ ROLE_USER,ROLE_AUTHENTIFIED ] }
          admin: { password: pass, roles: [ ROLE_ADMIN,ROLE_AUTHENTIFIED ] }
          ext1:  { password: pass1, roles: [ ROLE_EXTERNAL,ROLE_STUDENT2,ROLE_AUTHENTIFIED ] }
          ext2:  { password: pass2, roles: [ ROLE_EXTERNAL,ROLE_AUTHENTIFIED ] }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt|amu)|css|images|js|amu)/
      security: false

    amu_secured:
      provider: amu_users
      pattern: /.*
      switch_user: true
      anonymous:  ~ 
#      amu: true

    amu_external:
      provider: externals
      pattern: /ext/login.*
      security: false
      anonymous:  true 

    amu_rss:
      pattern: /rss.*
      security: false
      
#    amu_secured:
#      provider: amu_users
#      switch_user: true
#      pattern: ^/demo/* 
#      #^(ext/*)
#      security: true
#      anonymous:  ~ 
#      # { lifetime: 30 }
      
    http_secured:
      pattern: ^/demo/ext/*
      provider: in_memory 
      security: true
      #stateless: true
      http_basic:
        provider: in_memory
        realm: "ACCES EXTERNE"
#    bdd_secured:
#            form_login:  
#                login_path:  /login
#                check_path:  /login_check
            #          login_url: https://ident.univ-amu.fr:443/cas/login
#          logout_url: https://ident.univ-amu.fr:443/cas/logout
#          validation_url: https://ident.univ-amu.fr:443/cas/serviceValidate
#            logout:
#              target: /
          


            
  access_control:
  #  - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: /rss, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: /ext/login*, roles: [IS_AUTHENTICATED_ANONYMOUSLY], requires_channel: https }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_amu/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/demo/*^(personal|student), roles: [ROLE_USER] }
#    - { path: /demo/postit, roles: [ROLE_USER] }
#    - { path: /demo/table*, roles: [ROLE_USER] }
    - { path: ^/demo/ext/*, roles: [ROLE_EXTERNAL] }
    - { path: /demo/student, roles: [ROLE_STUDENT,ROLE_STUDENT2] }
    - { path: /demo/personal, roles: [ROLE_PERSONAL] }
    - { path: /campagnes/*, roles: [ROLE_MANAGER] }
    - { path: /messages/*, roles: [ROLE_ADMIN] }
    
  #  - { path: /(css|pictures|js)/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

  #        - { path: ^/, roles: ROLE_USER }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
